### ISSUE TITLE
Is this " step_length = int(window_length/2)" always be needed?

### ISSUE THREAD

**Issue by zhaozhh** [zafarrafii/Zaf-Python#1]
Dear Zafarrafii,

Is this " step_length = int(window_length/2)" always be needed in the stft?

**Comment by zafarrafii** [comment]
Hi Zhen-Hua,

Yes, you need a step or hop when you segment your audio signal into frames, before applying the Fourier transform to obtain the STFT. In this particular case, we use a step length of half the size of the window length, so that successive segments have 50% of overlap, for smoother transitions between frames and to have the constant-overlap add property.

Best,

Zafar

**Comment by zhaozhh** [comment]
Dear Zafar
Thank you for your answer! Do you know there is a stft function in the library scipy.signal ? But, I found if the lenght of data is not a integral multiple of the window's length,  the length of istft's return of scipy will not be the same with the oringal data. 

Did you have test you function sufficiently?

Best 
Zhen-Hua

**Comment by zafarrafii** [comment]
I believe there is an STFT function in SciPy, yes. That's normal; the iSTFT cannot predict the exact length of the original audio signal. Ideally, it should return something a tiny bit longer. You can then trim it if you want to compare it with your original audio signal.

Haha, that's a funny question :D Yes, I did test my function sufficiently. I mean there could always be bugs but I am pretty sure it's accurate ;)

Best,

Zafar

**Comment by zhaozhh** [comment]
Dear Zafar,
 "You can then trim it if you want to compare it with your original audio signal." that is very usefull to me, 
Thank you very much!
Best 
Hua

**Comment by zafarrafii** [comment]
Anytime!

Zafar
